feat[next]: Upgrade dace dependency to v1.0.0 (#1740)
DaCe version upgraded to `1.0.0`. It is also constrained to `< 1.1.0
`because the plan for DaCe v1.x is to introduce some breaking changes.

GPU tests still fail with GTIR DaCe backend (`test_double_use_scalar`)
so they will be enabled in a separate PR.

Additional changes:
- Removed limitation on SymPy version since DaCe is now compatible with
SymPy v1.13
- CUDA version upgraded from 11.2 to 11.4 to avoid this compile error in
gpu build:
`dace/codegen/../runtime/include/dace/math.h(499): error: A __device__
variable cannot be marked constexpr`