fix[next]: Fix different static args after `with_backend` (#2475)
The following snippet broke after #2368
```python
prg1 = prog.with_backend(gtfn.run_gtfn)
prg2 = prog.with_backend(gtfn.run_gtfn)

# compile with static args
prg1.compile(cond=[True], offset_provider={})

# compile without static args
prg2.compile(offset_provider={})
```
with the following error
```
ValueError: Argument descriptor StaticArg must be the same for all compiled programs, got [] expected ['cond'].
```
This PR avoids using `object.__setattr__` on the `CompilationOptions` to
pass information to the compiled program pool construction and instead
explicitly constructs the pool on `compile`.

Note that the `enable_jit` argument to `compile` has been removed and
replaced by:
```python
prg.with_compilation_option(enable_jit=...)
```
as the same `object.__setattr__` mechanism was used to pass the
information.