ci: bump minimum packaging version (#2936)
This is a fix for daily CI with `UV_RESOLUTION=lowest-direct`. The error
message looks like:
```
ImportError: Cannot import `packaging.licenses`.
  Setuptools>=77.0.0 requires "packaging>=24.2" to work properly.
  Please make sure you have a suitable version installed.
```